server {
    listen 8088;
    charset utf8;

    access_log  /app/www/TO-DO/logs/TO-DO_access.log;
    error_log   /app/www/TO-DO/logs/TO-DO_error.log error;

    location / {
        proxy_pass http://todosite:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}